### ISSUE TITLE
Game crashes when I try to join the official server.

### ISSUE THREAD

**Issue by xxmynamesucksxx** [The-1-7-10-Pack/The-1.7.10-Pack#103]
Whenever I try to join the Official server my game crashes mid load. My single player works, I do not get an error message in minecraft it just takes me back to the launcher. I have talked to fluke and done everything he has recommended and none of them have worked, I have re installed the modpack and that hasn't helped. I don't think it is a corrupt chunk since my friends can join the server fine and don't have any issues at my base.

*PLEASE USE A PASTE TOOL: http://paste.ubuntu.com/9867710*

**Comment by The-1-7-10-Pack** [comment]
I know Fluke did some changes on the official server, can you try again?

**Comment by xxmynamesucksxx** [comment]
Tried again still nothing, crashes me straight back the the launcher.

**Comment by Flukethoughts** [comment]
should be fixed and mynamesucks i need your crash report sent here but i can say i will be moving the server again soon

**Comment by xxmynamesucksxx** [comment]
Still crashes, and here is the crash log. http://paste.ubuntu.com/9874198/

**Comment by xxmynamesucksxx** [comment]
Problem has been solved.

**Comment by The-1-7-10-Pack** [comment]
Good.
