### ISSUE TITLE
setting the ram requirements location

### ISSUE THREAD

**Issue by Dommain** [The-1-7-10-Pack/The-1.7.10-Pack#256]
Based on what I read and saw on the forum the ram is set manually. I am still confused which file has the settings in it so I can delete them and I request the location of said settings. In game I have the ram at 75% running all the way to 99% pausing for 5 second, going back to 75% again. If I could set the ram higher to 4 to 5 gigs I would not lag at all with a huge active base.

http://i.imgur.com/65pMk2v.png

**Comment by frieder** [comment]
Based on what I see in <technic-launcher>/modpacks/the-1710-pack/bin/version.json it also seems that not only is the heap space limited to 3G (I usually play with 8G) but also the use of PermSize is fixed. Please take into account that -XX:MaxPermSize and -XX:PermSize are no longer available with Java 8 and have been replaced by -XX:MaxMetaspaceSize and -XX:MetaspaceSize. Therefore I would like to ask you to remove the default memory settings and let people assign their own values in the launcher.

**Comment by The-1-7-10-Pack** [comment]
@Dommain:
You had a look at the RAM when doing a backup. Usually it won't get to 90%, even though it's still not a problem. Using 4-5 is possible for pro users and I can explain it for you if you'd like, but I don't see any reason you should be afraid from using 75% of RAM.

@frieder:
1. Not everyone got Java 8.
2. You don't need more than 3GB, you're wasting you're RAM for nothin'.
3. People like to keep the RAM as default (1) and then complain that the modpack is laggy. They also like to set it up to 8 (which may be their computer maximum) and they will also complain that the modpack is buggy.
So, that's why this is the situation at the moment.
I know that FTB modpacks can set up a default RAM, that is still changeable, but for the awesome Technic Platform this is the best solution.

**Comment by frieder** [comment]
Thanks for taking the time to comment on this. You are right that not everybody has Java 8 but that is also true for Java 7. Also FYI Java 7 is scheduled for EOL by April 2015 so people will switch eventually.

As for your comment regarding the 3GB heap space I respectfully disagree. I wanted to use the Sphax 128x resource pack and 3GB is not enough when using this resource pack.. I can provide you with the log files that contain the OOM exceptions if you want me to but I guess you can easily reproduce this issue on your own.

**Comment by The-1-7-10-Pack** [comment]
@frieder I'd be an issue if Sphax 128x would even work on MC 1.7, but that's not true at all. MC 1.7 has old bugs with big resource packs that Mojang never believed will be a thing. And they are not a thing indeed on Vanilla, but Mojang can't give support for modded Minecraft, and that's why you'd have the same problem trying to use Sphax 128x in DW20's modpack, or just any heavy resource pack for any modpack. It's on the Developer Notes in the Sphax thread.

**Comment by frieder** [comment]
Ok this makes sense. Last time I played MC and used Sphax was with 1.6.x and there it worked. I assumed that since you link the patches for the 128-32 resource pack on the technic modpack page that it still works. It is a shame that it does not. Anyways thank you for pointing that out.

**Comment by The-1-7-10-Pack** [comment]
@frieder No problem, that's why I have this mini support center.
Have a nice day.
I hope I have answered @Dommain's questions too.

**Comment by Dommain** [comment]
The database back-up is not what is not what is causing the lag. Every about 15 seconds it climbs from 75% used to 99%, and then freezes for 5-8 seconds, goes back to 75% and cycles over and over. It only happens when I get near one of mega builds since it does not have enough ram to deal with the amount of blocks being seen at once.

I am just asking where to change it since I do not know where it is located.

**Comment by The-1-7-10-Pack** [comment]
@Dommain It is a problem with people's moster builds..
It is located on the version.json file in the bin folder of the modpack.
