### ISSUE TITLE
Problems with downloading the pack

### ISSUE THREAD

**Issue by CycloneBlitz** [The-1-7-10-Pack/The-1.7.10-Pack#586]
When i download the 1.7.10 pack with the link (api.technicpack.net/modpack/the-1710-pack) it said "{   "status": 401,   "error": "Request Unauthorized" }" and i cant download. 
Help please!

**Comment by The-1-7-10-Pack** [comment]
Should work now!

**Comment by CycloneBlitz** [comment]
Sir still not working for me. Is there another link or something? :(

**Comment by The-1-7-10-Pack** [comment]
You need to download the modpack through the Technic Launcher, not just through the URL.

**Comment by CycloneBlitz** [comment]
Ok thanks sir :)
