### ISSUE TITLE
Get error when trying to install

### ISSUE THREAD

**Issue by ThatPinkGuy709** [The-1-7-10-Pack/The-1.7.10-Pack#727]
I get the following error when trying to install the mod pack.
![untitled](https://cloud.githubusercontent.com/assets/13176902/8507994/32843024-2237-11e5-8cce-f61b3daad563.png)

**Comment by andalite49** [comment]
I am receiving this error as well, I already had the the modpack installed and attempted to get the newest version which resulted in the above error. I deleted the modpack and attempted to re-install and am getting the same error.

**Comment by The-1-7-10-Pack** [comment]
Some problems with our Solder may happened, it is fixed now :)

**Comment by DiasZ** [comment]
Hello, I am still getting this error, any idea on how to fix it?

**Comment by The-1-7-10-Pack** [comment]
Technic is overloaded, as I see it now.
Try again later :)
